stages:
  - Build
  - Plan and Validate
  - Deploy Infra
  - Deploy K8s 
  - Destroy Infra

Build:AWS:AMI:
  stage: Build
  image:
    name: hashicorp/packer:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    - cd base_image 
    - echo $BASTION | base64 -d > Bastion_Key.pem
    - chmod 400 Bastion_Key.pem 
  script:
    - packer build packer.json
  only:
    changes:
      - base_image/*

.terraform_job: &terraform_def
  image:
    name: hashicorp/terraform:0.11.9
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    - cd aws_provision
    - terraform init

Infra:Terraform:Validate:
  stage: Plan and Validate
  <<: *terraform_def
  script:
    - terraform validate .

Infra:Terraform:Plan:
  stage: Plan and Validate 
  <<: *terraform_def
  script:
    - terraform plan

Infra:Terraform:Apply:
  stage: Deploy Infra
  <<: *terraform_def
  script:
    - terraform apply -auto-approve
  when: manual
  artifacts:
    paths:
      - kubeadm_create/hosts

Infra:Ansible:K8s-Deploy-Cluster:
  image: ansible/ansible-runner
  stage: Deploy K8s 
  before_script:
    - cd kubeadm_create
    - echo $BASTION | base64 -d > Bastion_Key.pem
    - chmod 400 Bastion_Key.pem 

  script:
    - ansible-playbook -i hosts master.yml
    - ansible-playbook -i hosts nodes.yml

Terraform:destroy:
  stage: Destroy Infra
  <<: *terraform_def
  script:
    - terraform destroy -auto-approve
  when: manual
