stages:
  - build
  - validate
  - plan
  - apply
  - destroy

build_ami_base:
  stage: build
  image:
    name: hashicorp/packer:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    - cd base_image 
    - echo $BASTION | base64 -d > Bastion_Key.pem
    - chmod 400 Bastion_Key.pem 
  script:
    - packer build packer.json
  only:
    changes:
      - base_image/*

.terraform_job: &terraform_def
  image:
    name: hashicorp/terraform:0.11.9
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    - cd aws_provision
    - terraform init

terraform:validate:
  stage: validate
  <<: *terraform_def
  script:
    - terraform validate .
  allow_failure: true

terraform:plan:
  stage: plan
  <<: *terraform_def
  script:
    - terraform plan

terraform:apply:
  stage: apply
  <<: *terraform_def
  script:
    - terraform apply -auto-approve
  when: manual

terraform:destroy:
  stage: destroy
  <<: *terraform_def
  script:
    - terraform destroy -auto-approve
  when: manual
